### ISSUE TITLE
Generating tzdb..." occurs on every build even when building it in a separate project

### ISSUE THREAD

**Issue by pmeheut** [cquiroz/sbt-tzdb#132]
I read issue https://github.com/cquiroz/sbt-tzdb/issues/88#issue-874044652 as well as https://github.com/an-tex/sc8s/pull/66#issue-1014934060

Whatever I do, my build.sbt recompiles tzdb every time even if it is in a separate project with no dependencies on.

Is there a way to avoid it?

**Comment by cquiroz** [comment]
At least I have my tzdb generati in a complitely separate module and I get the artifacts via maven. Would that work?

**Comment by pmeheut** [comment]
Yes, that would work fine.

**Comment by povder** [comment]
https://github.com/cquiroz/sbt-tzdb/pull/135 PR fixes it I think

**Comment by cquiroz** [comment]
I think this can be closed

**Comment by pmeheut** [comment]
Yes. Sorry, I had no time to look at it because of the holidays.
Thanks.
