### ISSUE TITLE
Add support for Scala 3.0.0

### ISSUE THREAD

**Issue by Lasering** [cquiroz/sbt-tzdb#154]
I have a Scala 3.0.0 project with very strict compiler flags:

```
scalacOptions ++= Seq(
    "-indent",                       // Allow significant indentation.
    "-new-syntax",                   // Require `then` and `do` in control expressions.
    "-feature",                      // Emit warning and location for usages of features that should be imported explicitly.
    "-language:future",              // better-monadic-for
    "-language:implicitConversions", // Allow implicit conversions
    "-deprecation",                  // Emit warning and location for usages of deprecated APIs.
    "-Werror",                       // Fail the compilation if there are any warnings.
    "-source:future",
    (...)
)
```

The generated sources namely the `TzdbZoneRulesProvider` is causing errors such as:
```
[error] -- Error: /home/simon/Documents/SimulaEV/modules/frontend/target/scala-3.1.1/src_managed/main/java/time/zone/TzdbZoneRulesProvider.scala:16:26 
[error] 16 |  import zonedb.java.tzdb._
[error]    |                          ^
[error]    |`_` is no longer supported for a wildcard import; use `*` instead
[error]    |This construct can be rewritten automatically under -rewrite -source future-migration.
[error] -- Error: /home/simon/Documents/SimulaEV/modules/frontend/target/scala-3.1.1/src_managed/main/java/time/zone/TzdbZoneRulesProvider.scala:54:23 
[error] 54 |    val dayOfWeek = if (zor(2) >= 0) DayOfWeek.of(zor(2)) else null
[error]    |                       ^^^^^^^^^^^^^
[error]    |This construct is not allowed under -new-syntax.
[error]    |This construct can be rewritten automatically under -new-syntax -rewrite -source 3.0-migration.
```

Any suggestion on how to fix it? I see the code is generated via a sourceGenerators, maybe its possible to add another sourceGenerator that would recompile with `-new-syntax -rewrite -future-migration` (if that is even something sbt will allow).

PS: I'm trying to avoid following the [suggestion of creating a subproject just for this](https://stackoverflow.com/questions/35049913/is-it-possible-to-compile-managed-source-with-different-compiler-flags-than-unma) as it would complicate my setup a lot.

**Comment by cquiroz** [comment]
Right, I noted this problem long ago but it maybe hard to generate code that would either crosscompile or generate different code for scala 2-3. My approach has been the external project as you mention

I'm totally open to integrate a PR if there is any solution

**Comment by Lasering** [comment]
Looking at the code seems like the `TzdbZoneRulesProvider` is coming from `src/main/resources/{js,jvm,native}`. Would you be open to the possibility of having multiple files there? For example
```
js/scala-2/TzdbZoneRulesProvider.scala
js/scala-3/TzdbZoneRulesProvider.scala
js/scala-3-future/TzdbZoneRulesProvider.scala
```
And then a sbt setting would allow fine tunning of which file would be choosen. Or with a little more work this could be automatically chosen looking at the scalaVersion and scalacOptions.

**Comment by cquiroz** [comment]
I guess that would be the simplest approach, I'm not sure how to pick one depending on the scala version

**Comment by Lasering** [comment]
Lets say the setting would be `generatedSourceDialect` with possible values:

The plugin is being included in a given sbt project. The default value for the `generatedSourceDialect` would be computed by looking at the given sbt project scalaVersion (assuming this is something sbt allows). The implementation would be akin to this pseudocode:

```
if major scalaVersion == 3 then
  if scalacOptions.exists(_.contains("future")) then
    generatedSourceDialect := Dialect.Scala3Future
  else
    generatedSourceDialect := Dialect.Scala3
else
  generatedSourceDialect := Dialect.Scala2
```

Maybe more dialects would be needed to support `-new-syntax` and `-indent`.

The problem with this approach is maintaining all the files in sync with each other. Although that could be automated by have the authoritative file be the Scala2 one and generating the Scala3 files with `-rewrite`.

**Comment by cquiroz** [comment]
I think that could be fine. the syntax doesn't change that often anyway

**Comment by cquiroz** [comment]
Had some troubles with the release but versin 3.0.0 should be on its way to maven central
