### ISSUE TITLE
Compilation error "not found: type ZoneMap" 

### ISSUE THREAD

**Issue by SandroGrzicic** [cquiroz/sbt-tzdb#7]
Hi,

I'm using Scala 2.12.7, scala.js 0.6.25 and sbt 1.2.6.
 
I've just added the plugin to my plugins.sbt as follows:

    addSbtPlugin("io.github.cquiroz" % "sbt-tzdb" % "0.3.0")

And added the plugin to my client projects, as well as configured it, as follows:

    lazy val client1 = project.in(file("client1")).enablePlugins(TzdbPlugin)
        .settings(zonesFilter := {(z: String) => z == "Europe/London"}

    lazy val client2 = project.in(file("client2")).enablePlugins(TzdbPlugin)
        .settings(zonesFilter := {(z: String) => z == "Europe/London"}

    lazy val client3 = project.in(file("client3")).enablePlugins(TzdbPlugin)
        .settings(zonesFilter := {(z: String) => z == "Europe/London"}

    lazy val shared = crossProject(JVMPlatform, JSPlatform)
        .jsConfigure(_.enablePlugins(TzdbPlugin))
        .settings(zonesFilter := {(z: String) => z == "Europe/London"}

    lazy val sharedJvm = shared.jvm
    lazy val sharedJs = shared.js

(Note: the above configuration is simplified; I have other plugins enabled as well - e.g. ScalaJSPlugin, ScalaJSWeb, JSDependenciesPlugin, ScalaJSBundlerPlugin)

When compiling the project, I get the following output:

```
sbt:client1> compile
[info] tzdb data missing. downloading latest version to (...)\client1\target\scala-2.12\resource_managed\main\tzdb...
[info] downloading from http://www.iana.org/time-zones/repository/tzdata-latest.tar.gz
[info] to file (...)\client1\target\scala-2.12\resource_managed\main\tzdb.tar.gz
[info] Updating ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 5 Scala sources to (...)\shared\.js\target\scala-2.12\classes ...
[error] (...)\shared\.js\target\scala-2.12\src_managed\main\java\time\zone\TzdbZoneRulesProvider.scala:110:21: not found: type ZoneMap
[error]         val r = new ZoneMap[String, ZoneRules]
[error]                     ^
[error] one error found
[info] Generating tzdb from db at (...)\client1\target\scala-2.12\resource_managed\main\tzdb to (...)\client1\target\scala-2.12\src_managed\main
[error] (sharedJS / Compile / compileIncremental) Compilation failed
[error] Total time: 6 s, completed 25.11.2018. 21:53:18
sbt:client1>    
```

Any idea what am I doing wrong? Thanks.

**Comment by cquiroz** [comment]
I think you need to add `scala-java-time` as a dependency

**Comment by SandroGrzicic** [comment]
> I think you need to add `scala-java-time` as a dependency

You're right - I added the dependency to my `client `projects, but didn't add it to the `shared` project. Adding that dependency it to the JS subproject of the `shared` fixed the issue. Thanks!
